data:
  source_url : "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  data_dir : data
  source_zipped_data_dir: zip data
  source_filename: data.zip
  unzip_data_dir: unzipped_data
  bad_data_dir: bad_data
  parent_data_dir: PetImages